# Generated by Django 6.0.2 on 2026-05-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bookedslot_doctorschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receiving_account',
            field=models.CharField(blank=True, choices=[('ucb', 'UCB Bank'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('upay', 'Upay'), ('cash', 'Cash')], help_text='Admin account that received this payment', max_length=20, null=True),
        ),
    ]
