# Generated by Django 6.0.2 on 2026-05-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_payment_receiving_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='track_number',
            field=models.PositiveIntegerField(default=1, help_text='Track number for calculation (1=Depression, 2=Anxiety, 3=Sleep, 4=Energy)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='expertise_tags',
            field=models.JSONField(default=list, help_text="Keywords for sub-symptom matching (e.g., ['insomnia', 'panic-attacks'])"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients_helped',
            field=models.PositiveIntegerField(default=0, help_text='Total number of patients helped'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='primary_focus',
            field=models.CharField(choices=[('Depression', 'Depression'), ('Anxiety', 'Anxiety'), ('General Stress', 'General Stress')], default='General Stress', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='review_rating',
            field=models.FloatField(default=0.0, help_text='Average patient review score (0.0-5.0)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='success_rate',
            field=models.FloatField(default=0.0, help_text='Treatment success rate percentage'),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='category',
            field=models.CharField(choices=[('Depression', 'Depression'), ('Anxiety', 'Anxiety'), ('Sleep', 'Sleep'), ('Energy', 'Energy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Psychiatrist', 'Psychiatrist'), ('Clinical Psychologist', 'Clinical Psychologist'), ('Psychologist', 'Psychologist'), ('Therapist', 'Therapist'), ('Counselor', 'Counselor')], max_length=255),
        ),
    ]
