# Generated by Django 6.0.2 on 2026-05-11 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_add_advanced_doctor_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='professional_summary',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='review_rating',
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_online',
            field=models.BooleanField(default=True, help_text='Available for online consultations'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(default='', help_text='Professional biography'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_support',
            field=models.BooleanField(default=False, help_text='Provides emergency/crisis support'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='', help_text="Doctor's full name", max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=5.0, help_text='Patient rating (0.0-5.0)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(default=0, help_text='Years of clinical experience'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='expertise_tags',
            field=models.JSONField(default=list, help_text="Clinical expertise tags (e.g., ['insomnia', 'panic-attacks'])"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='primary_focus',
            field=models.CharField(choices=[('Depression', 'Depression'), ('Anxiety', 'Anxiety'), ('Stress', 'Stress'), ('Sleep', 'Sleep')], default='Stress', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Psychiatrist', 'Psychiatrist'), ('Clinical Psychologist', 'Clinical Psychologist'), ('Psychologist', 'Psychologist'), ('Therapist', 'Therapist'), ('Counselor', 'Counselor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClinicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phq9_score', models.IntegerField(help_text='PHQ-9 depression score (0-27)')),
                ('depression_severity', models.CharField(choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('moderately_severe', 'Moderately Severe'), ('severe', 'Severe')], max_length=20)),
                ('gad7_score', models.IntegerField(help_text='GAD-7 anxiety score (0-21)')),
                ('anxiety_severity', models.CharField(choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('primary_condition', models.CharField(help_text='Primary condition: Depression or Anxiety', max_length=20)),
                ('emergency_risk', models.BooleanField(default=False, help_text='Suicide risk detected (Q9 >= 2)')),
                ('suicide_risk_level', models.CharField(default='none', help_text='Suicide risk level', max_length=20)),
                ('phq9_responses', models.JSONField(help_text='PHQ-9 question responses (0-3 each)')),
                ('gad7_responses', models.JSONField(help_text='GAD-7 question responses (0-3 each)')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('session_duration', models.IntegerField(help_text='Time taken to complete assessment (seconds)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
