# Generated by Django 6.0.2 on 2026-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_add_clinical_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='primary_focus',
            field=models.CharField(choices=[('Depression', 'Depression'), ('Anxiety', 'Anxiety'), ('Stress', 'Stress'), ('Sleep', 'Sleep'), ('Schizophrenia', 'Schizophrenia'), ('OCD', 'OCD'), ('Neurological Disorders', 'Neurological Disorders'), ('Talk Therapy', 'Talk Therapy'), ('Emotional Healing', 'Emotional Healing'), ('Substance Abuse', 'Substance Abuse'), ('Alcohol Addiction', 'Alcohol Addiction'), ('Recovery Programs', 'Recovery Programs')], default='Stress', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Psychiatrist', 'Psychiatrist'), ('Clinical Psychologist', 'Clinical Psychologist'), ('Psychologist', 'Psychologist'), ('Therapist', 'Therapist'), ('Counselor', 'Counselor'), ('Geriatric Psychologist', 'Geriatric Psychologist'), ('Addiction Specialist', 'Addiction Specialist'), ('Neuropsychiatrist', 'Neuropsychiatrist')], max_length=50),
        ),
    ]
