# Generated by Django 6.0.2 on 2026-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_doctor_primary_focus_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Psychiatrist', 'Psychiatrist'), ('Clinical Psychologist', 'Clinical Psychologist'), ('Psychologist', 'Psychologist'), ('Therapist', 'Therapist'), ('Counselor', 'Counselor'), ('Geriatric Psychologist', 'Geriatric Psychologist'), ('Addiction Specialist', 'Addiction Specialist'), ('Neuropsychiatrist', 'Neuropsychiatrist'), ('Child Psychiatrist', 'Child Psychiatrist'), ('Child Psychologist', 'Child Psychologist'), ('Adolescent Psychiatrist', 'Adolescent Psychiatrist'), ('Forensic Psychiatrist', 'Forensic Psychiatrist'), ('Sports Psychologist', 'Sports Psychologist'), ('Organizational Psychologist', 'Organizational Psychologist'), ('Health Psychologist', 'Health Psychologist'), ('Educational Psychologist', 'Educational Psychologist'), ('Rehabilitation Psychologist', 'Rehabilitation Psychologist'), ('Neuropsychologist', 'Neuropsychologist'), ('Behavioral Psychologist', 'Behavioral Psychologist'), ('Cognitive Psychologist', 'Cognitive Psychologist'), ('Developmental Psychologist', 'Developmental Psychologist'), ('Social Psychologist', 'Social Psychologist'), ('Marriage and Family Therapist', 'Marriage and Family Therapist'), ('Art Therapist', 'Art Therapist'), ('Music Therapist', 'Music Therapist'), ('Occupational Therapist', 'Occupational Therapist'), ('Psychoanalyst', 'Psychoanalyst'), ('Psychopharmacologist', 'Psychopharmacologist')], max_length=50),
        ),
    ]
