# Generated by Django 6.0.2 on 2026-05-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_doctor_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
    ]
