# Generated by Django 6.0.2 on 2026-05-20 00:01

from django.db import migrations, models


SPECIALIZATION_CHOICES = [
    ('Psychiatrist', 'Psychiatrist'),
    ('Clinical Psychologist', 'Clinical Psychologist'),
    ('Therapist', 'Therapist'),
    ('Counselor', 'Counselor'),
    ('Child Psychiatrist', 'Child Psychiatrist'),
    ('Child Psychologist', 'Child Psychologist'),
    ('Geriatric Psychologist', 'Geriatric Psychologist'),
    ('Addiction Specialist', 'Addiction Specialist'),
    ('Marriage and Family Therapist', 'Marriage and Family Therapist'),
    ('Neuropsychiatrist', 'Neuropsychiatrist'),
    ('Neuropsychologist', 'Neuropsychologist'),
]

PRIMARY_FOCUS_CHOICES = [
    ('Depression', 'Depression'),
    ('Anxiety', 'Anxiety'),
    ('Stress', 'Stress'),
    ('Sleep', 'Sleep'),
    ('Schizophrenia', 'Schizophrenia'),
    ('OCD', 'OCD'),
    ('Neurological Disorders', 'Neurological Disorders'),
    ('Talk Therapy', 'Talk Therapy'),
    ('Emotional Healing', 'Emotional Healing'),
    ('Substance Abuse', 'Substance Abuse'),
    ('Alcohol Addiction', 'Alcohol Addiction'),
    ('Recovery Programs', 'Recovery Programs'),
]


def seed_options_and_migrate_doctors(apps, schema_editor):
    Doctor = apps.get_model('home', 'Doctor')
    DoctorSpecialization = apps.get_model('home', 'DoctorSpecialization')
    DoctorPrimaryFocus = apps.get_model('home', 'DoctorPrimaryFocus')

    specializations = {}
    for index, (value, label) in enumerate(SPECIALIZATION_CHOICES):
        option, _created = DoctorSpecialization.objects.update_or_create(
            value=value,
            defaults={'label': label, 'sort_order': index, 'is_active': True},
        )
        specializations[value] = option

    focuses = {}
    for index, (value, label) in enumerate(PRIMARY_FOCUS_CHOICES):
        option, _created = DoctorPrimaryFocus.objects.update_or_create(
            value=value,
            defaults={'label': label, 'sort_order': index, 'is_active': True},
        )
        focuses[value] = option

    for doctor in Doctor.objects.all():
        legacy_specialty = getattr(doctor, 'specialty', None)
        legacy_focus = getattr(doctor, 'primary_focus', None) or 'Stress'

        specialization = specializations.get(legacy_specialty) or specializations.get('Therapist')
        focus = focuses.get(legacy_focus) or focuses.get('Stress')

        if specialization:
            doctor.specializations.add(specialization)
        if focus:
            doctor.primary_focuses.add(focus)


def restore_legacy_doctor_fields(apps, schema_editor):
    Doctor = apps.get_model('home', 'Doctor')
    for doctor in Doctor.objects.all():
        specialization = doctor.specializations.order_by('sort_order', 'label').first()
        focus = doctor.primary_focuses.order_by('sort_order', 'label').first()
        doctor.specialty = specialization.value if specialization else 'Therapist'
        doctor.primary_focus = focus.value if focus else 'Stress'
        doctor.save(update_fields=['specialty', 'primary_focus'])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_doctor_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPrimaryFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Doctor primary focuses',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='primary_focuses',
            field=models.ManyToManyField(related_name='doctors', to='home.doctorprimaryfocus'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(related_name='doctors', to='home.doctorspecialization'),
        ),
        migrations.RunPython(seed_options_and_migrate_doctors, restore_legacy_doctor_fields),
        migrations.RemoveField(
            model_name='doctor',
            name='primary_focus',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
    ]
