# Generated by Django 6.0.2 on 2026-05-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_doctorprimaryfocus_doctorspecialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=160)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', models.JSONField(default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='home_chatbo_source__a2fab3_idx'), models.Index(fields=['content_hash'], name='home_chatbo_content_148191_idx')],
                'unique_together': {('source_type', 'source_id', 'chunk_index')},
            },
        ),
    ]
