# Generated by Django 6.0.2 on 2026-05-21 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_chatsession_chatmessage_emergencylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceiverAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank Transfer')], max_length=20)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('merchant_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('routing_number', models.CharField(blank=True, max_length=30)),
                ('card_processor_name', models.CharField(blank=True, max_length=150)),
                ('api_key', models.CharField(blank=True, help_text='Optional provider API key. Leave unchanged unless rotating it.', max_length=255)),
                ('secret_key', models.CharField(blank=True, help_text='Optional provider secret key. Leave unchanged unless rotating it.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Receiver Account',
                'verbose_name_plural': 'Payment Receiver Accounts',
                'ordering': ['payment_method', '-is_active', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(help_text='SMTP host, for example smtp.gmail.com', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1)])),
                ('email_host_user', models.EmailField(help_text='SMTP username or Gmail address', max_length=254)),
                ('email_host_password', models.CharField(blank=True, help_text='SMTP app password or provider password. Leave unchanged when editing unless rotating it.', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('default_from_email', models.EmailField(help_text='Address used as the sender for platform emails', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Email Config',
                'verbose_name_plural': 'System Email Config',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
