# Generated by Django 6.0.2 on 2026-05-21 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_task_completion_patients(apps, schema_editor):
    TaskCompletion = apps.get_model('home', 'TaskCompletion')
    for completion in TaskCompletion.objects.select_related('daily_task').filter(patient__isnull=True):
        if completion.daily_task_id and completion.daily_task.patient_id:
            completion.patient_id = completion.daily_task.patient_id
            completion.save(update_fields=['patient'])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_payment_receiving_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcompletion',
            options={'verbose_name': 'Daily Task Completion', 'verbose_name_plural': 'Daily Task Completions'},
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_task_completion_patients, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dailytask',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.consultation'),
        ),
        migrations.CreateModel(
            name='DailyTaskReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('email_sent_at', models.DateTimeField(auto_now_add=True)),
                ('incomplete_tasks_count', models.PositiveIntegerField(default=0)),
                ('incomplete_task_titles', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Task Reminder Log',
                'verbose_name_plural': 'Daily Task Reminder Logs',
                'ordering': ['-date', '-email_sent_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
