# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_payment_paid_at_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='duration_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='priority',
            field=models.CharField(
                choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')],
                default='medium',
                max_length=10,
            ),
        ),
    ]
