# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_dailytask_duration_days_dailytask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending_payment', 'Pending Payment'),
                    ('scheduled', 'Scheduled'),
                    ('confirmed', 'Confirmed'),
                    ('waiting', 'Waiting'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                    ('incomplete', 'Incomplete'),
                    ('expired', 'Expired'),
                    ('cancelled', 'Cancelled'),
                ],
                default='scheduled',
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='consultation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(
                choices=[
                    ('scheduled', 'Scheduled'),
                    ('waiting', 'Waiting'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                    ('incomplete', 'Incomplete'),
                    ('expired', 'Expired'),
                    ('cancelled', 'Cancelled'),
                ],
                default='scheduled',
                max_length=15,
            ),
        ),
    ]
