# Generated by Codex on 2026-05-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_payment_participants(apps, schema_editor):
    Payment = apps.get_model('home', 'Payment')
    for payment in Payment.objects.select_related('appointment').filter(
        models.Q(patient__isnull=True) | models.Q(doctor__isnull=True)
    ):
        appointment = payment.appointment
        payment.patient_id = appointment.patient_id
        payment.doctor_id = appointment.doctor_id
        payment.save(update_fields=['patient', 'doctor'])


def normalize_payment_statuses(apps, schema_editor):
    Payment = apps.get_model('home', 'Payment')
    Payment.objects.filter(status='processing').update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_consultation_status_and_join_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='payment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.doctor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_number_masked',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('otp_sent', 'OTP Sent'),
                    ('test_paid', 'Test Paid'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('cancelled', 'Cancelled'),
                    ('refunded', 'Refunded'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.RunPython(normalize_payment_statuses, migrations.RunPython.noop),
        migrations.RunPython(populate_payment_participants, migrations.RunPython.noop),
    ]
