# Generated by Codex on 2026-05-27

from django.db import migrations, models
import django.db.models.deletion


def backfill_payment_receivers(apps, schema_editor):
    Payment = apps.get_model('home', 'Payment')
    PaymentReceiverAccount = apps.get_model('home', 'PaymentReceiverAccount')

    def mask_identifier(value, prefix=3, suffix=3):
        if not value:
            return ''
        if len(value) <= prefix + suffix:
            return '*' * len(value)
        return f"{value[:prefix]}{'*' * 5}{value[-suffix:]}"

    def display_identifier(receiver):
        if receiver.payment_method in {'bkash', 'nagad'}:
            return mask_identifier(receiver.merchant_number or receiver.account_number)
        if receiver.payment_method == 'card':
            return receiver.card_processor_name
        return mask_identifier(receiver.account_number)

    for account in PaymentReceiverAccount.objects.filter(is_active=True, is_default=True):
        PaymentReceiverAccount.objects.filter(
            payment_method=account.payment_method,
            is_default=True,
        ).exclude(pk=account.pk).update(is_default=False)

    for payment in Payment.objects.all():
        method = payment.payment_method or payment.receiving_account or ''
        payment.receiver_payment_method = method
        if method:
            receiver = PaymentReceiverAccount.objects.filter(
                payment_method=method,
                is_active=True,
            ).order_by('-is_default', '-updated_at').first()
            if receiver:
                payment.payment_receiver_account_id = receiver.pk
                payment.receiver_account_snapshot = {
                    'id': receiver.pk,
                    'payment_method': receiver.payment_method,
                    'account_name': receiver.account_name,
                    'display_identifier': display_identifier(receiver),
                    'instructions': receiver.instructions,
                }
        payment.save(update_fields=[
            'receiver_payment_method',
            'payment_receiver_account',
            'receiver_account_snapshot',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_payment_checkout_test_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='systememailconfig',
            name='admin_notification_email',
            field=models.EmailField(blank=True, help_text='Where admin/test notifications should be sent.', max_length=254),
        ),
        migrations.AddField(
            model_name='systememailconfig',
            name='name',
            field=models.CharField(default='Primary website email', help_text='Admin label for this email setup.', max_length=120),
        ),
        migrations.AddField(
            model_name='systememailconfig',
            name='receive_email',
            field=models.EmailField(blank=True, help_text='Optional mailbox used for inbound/reply handling.', max_length=254),
        ),
        migrations.AddField(
            model_name='systememailconfig',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Support contact shown in platform emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='paymentreceiveraccount',
            name='card_receiver_account',
            field=models.CharField(blank=True, help_text='Settlement account or merchant identifier for card payments.', max_length=150),
        ),
        migrations.AddField(
            model_name='paymentreceiveraccount',
            name='instructions',
            field=models.TextField(blank=True, help_text='Safe public payment instructions shown to patients. Do not include secrets.'),
        ),
        migrations.AddField(
            model_name='paymentreceiveraccount',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use this account by default for this payment method.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_receiver_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='home.paymentreceiveraccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiver_account_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiver_payment_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(backfill_payment_receivers, migrations.RunPython.noop),
    ]
