# Generated by Django 6.0.2 on 2026-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_admin_email_payment_receiver_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
