# Generated by Django 6.0.2 on 2026-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_appointment_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='auto_complete_after_doctor_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_join_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_last_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_join_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_last_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
