# Generated by Django 6.0.2 on 2026-06-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_consultation_auto_complete_after_doctor_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_reminder', 'Task Reminder'), ('task_incomplete', 'Incomplete Task'), ('prescription_update', 'Prescription Update'), ('appointment_reminder', 'Appointment Reminder'), ('message', 'Message'), ('system', 'System Notification')], max_length=20),
        ),
    ]
