# Generated by Django 5.2.12 on 2026-06-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='option_choices',
            field=models.JSONField(blank=True, default=list, help_text='List of answer options with scores.'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('likert_scale', 'Likert Scale'), ('yes_no', 'Yes / No'), ('text', 'Text')], default='single_choice', max_length=30),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='reverse_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
